storagedir: /lustre/work/akira.tokiwa/Projects/LensingSSC/data # Path to the data directory
nside: 8192 # Nside of the map
npatch: 273 # Number of patches
patch_size: 10 # Size of the patches in degrees
xsize: 2048 # Size of the map in pixels
nbin: 15 # Number of bins in each statistic
lmin: 300 # Minimum ell
lmax: 3000 # Maximum ell
scale_angle: 5 # Scale angle for the smoothing
ngal: 30 # Number of galaxies in arcmin^2, galaxy shape noise
nest: true # Healpix ordering
zs_list:  # List of source redshifts
- 0.5
- 1.0
- 2.0
- 3.0